flow_order:
  - Input
  - Data
  - Embedding
  - Clustering
  - Filtering
  - POSFiltering
  - Weighting
  - Writer

input:
  # data_source: "data\\corpus_top10.csv"
  data_source: "data\\queries_samples.csv"  
#  data_source: "data\\corpus_top50.csv"

data:
  method: "PandasTask"

embedding:
  method: "GensimEmbeddingTask"
  data_source: "data\\wiki-news-300d-1M.vec"
  binary: False
  vocabulary: "data\\vocabulary_corpus_top50.csv"

clustering:
  method: "HnswTask"
  num_neighbors: 200
  num_threads: 4

filtering:
  method: "ThresholdTask"
  threshold_value: 1.

posfiltering:
  method: "PartOfSpeechTask"
  pos_filters:
    - "ADP"
    - "VERB"
    - "SYM"
    - "NUM"
    - "X"
    - "SCONJ"
    - "PUNCT"
    - "AUX"
    - "CONJ"
  
weighting:
  method: "TfTask"

writer:
  method: "WriterTask"
  # cluwords_repr_path: "data_output\\cw_corpus_thresh_1.0_pos.npz"
  # data_path: "data_output\\corpus_thresh_1.0_pos.parquet"
  cluwords_repr_path: "data_output\\cw_thresh_1.0_pos.npz"
  data_path: "data_output\\queries_thresh_1.0_pos.parquet"