flow_order:
  - Input
  - Data
  - Embedding
  - Clustering
  - Filtering
  - Weighting

input:
  data_source: "data\\queries_samples.csv"
#  data_source: "data\\corpus_top50.csv"

data:
  method: "PandasTask"

embedding:
  method: "GensimEmbeddingTask"
  data_source: "data\\wiki-news-300d-1M.vec"
  binary: False
  vocabulary: "data\\vocabulary_corpus_top50.csv"

clustering:
  method: "HnswTask"
  num_neighbors: 200
  num_threads: 4

filtering:
  method: "ThresholdTask"
  threshold_value: 0.8

weighting:
  method: "TfTask"