flow_order:
  - Input
  - Data
  - Embedding
  - Clustering
  - Filtering
  - Weighting
  - Writer

input:
  data_source: "data\\dropPre.csv"  

data:
  method: "PandasTask"

embedding:
  method: "GensimEmbeddingTask"
  data_source: "data\\wiki-news-300d-1M.vec"
  binary: False
  vocabulary: "data\\vocabulary_dropPre.csv"

clustering:
  method: "HnswTask"
  num_neighbors: 200
  num_threads: 4

filtering:
  method: "ThresholdTask"
  threshold_value: .4

weighting:
  method: "TfTask"

writer:
  method: "WriterTask"
  cluwords_repr_path: "data_output\\cw_repr_thresh_0.4_dropPre.npz"
  data_path: "data_output\\cw_repr_thresh_0.4_dropPre.parquet"
  